# Email Configuration for 'default' profile
# Ensure this 'From' address is allowed by your msmtp configuration (provider)
email_from = "sms-notifier@yourserver.com"
email_to = "youremail@example.com"
